apiVersion: skaffold/v4beta10
kind: Config
build:
  artifacts:
  - image: esaleovic/client
    context: client
    sync:
      manual:
      - src: src/**/*.js
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: esaleovic/comments
    context: client
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: esaleovic/event-bus
    context: client
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: esaleovic/moderation
    context: client
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: esaleovic/posts
    context: client
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: esaleovic/query
    context: client
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}
